export default [
    {surah:"1", name: "الفاتحة"},
	{surah:"2", name: "البقرة"},
	{surah:"3", name: "آل عمران"},
	{surah:"4", name: "النساء"},
	{surah:"5", name: "المائدة"},
	{surah:"6", name: "الأنعام"},
	{surah:"7", name: "الأعراف"},
	{surah:"8", name: "الأنفال"},
	{surah:"9", name: "التوبة"},
	{surah:"10", name: "يونس"},
	{surah:"11", name: "هود"},
	{surah:"12", name: "يوسف"},
	{surah:"13", name: "الرعد"},
	{surah:"14", name: "ابراهيم"},
	{surah:"15", name: "الحجر"},
	{surah:"16", name: "النحل"},
	{surah:"17", name: "الإسراء"},
	{surah:"18", name: "الكهف"},
	{surah:"19", name: "مريم"},
	{surah:"22", name: "طه"},
	{surah:"22", name: "الأنبياء"},
	{surah:"22", name: "الحج"},
	{surah:"23", name: "المؤمنون"},
	{surah:"24", name: "النور"},
	{surah:"25", name: "الفرقان"},
	{surah:"26", name: "الشعراء"},
	{surah:"27", name: "النمل"},
	{surah:"28", name: "القصص"},
	{surah:"29", name: "العنكبوت"},
	{surah:"30", name: "الروم"},
	{surah:"31", name: "لقمان"},
	{surah:"32", name: "السجدة"},
	{surah:"33", name: "الأحزاب"},
	{surah:"34", name: "سبإ"},
	{surah:"35", name: "فاطر"},
	{surah:"36", name: "يس"},
	{surah:"37", name: "الصافات"},
	{surah:"38", name: "ص"},
	{surah:"39", name: "الزمر"},
	{surah:"40", name: "غافر"},
	{surah:"41", name: "فصلت"},
	{surah:"42", name: "الشورى"},
	{surah:"43", name: "الزخرف"},
	{surah:"44", name: "الدخان"},
	{surah:"45", name: "الجاثية"},
	{surah:"46", name: "الأحقاف"},
	{surah:"47", name: "محمد"},
	{surah:"48", name: "الفتح"},
	{surah:"49", name: "الحجرات"},
	{surah:"50", name: "ق"},
	{surah:"51", name: "الذاريات"},
	{surah:"52", name: "الطور"},
	{surah:"53", name: "النجم"},
	{surah:"54", name: "القمر"},
	{surah:"55", name: "الرحمن"},
	{surah:"56", name: "الواقعة"},
	{surah:"57", name: "الحديد"},
	{surah:"58", name: "المجادلة"},
	{surah:"59", name: "الحشر"},
	{surah:"60", name: "الممتحنة"},
	{surah:"61", name: "الصف"},
	{surah:"62", name: "الجمعة"},
	{surah:"63", name: "المنافقون"},
	{surah:"64", name: "التغابن"},
	{surah:"65", name: "الطلاق"},
	{surah:"66", name: "التحريم"},
	{surah:"67", name: "الملك"},
	{surah:"68", name: "القلم"},
	{surah:"69", name: "الحاقة"},
	{surah:"70", name: "المعارج"},
	{surah:"71", name: "نوح"},
	{surah:"72", name: "الجن"},
	{surah:"73", name: "المزمل"},
	{surah:"74", name: "المدثر"},
	{surah:"75", name: "القيامة"},
	{surah:"76", name: "الانسان"},
	{surah:"77", name: "المرسلات"},
	{surah:"78", name: "النبإ"},
	{surah:"79", name: "النازعات"},
	{surah:"80", name: "عبس"},
	{surah:"81", name: "التكوير"},
	{surah:"82", name: "الإنفطار"},
	{surah:"83", name: "المطففين"},
	{surah:"84", name: "الإنشقاق"},
	{surah:"85", name: "البروج"},
	{surah:"86", name: "الطارق"},
	{surah:"87", name: "الأعلى"},
	{surah:"88", name: "الغاشية"},
	{surah:"89", name: "الفجر"},
	{surah:"90", name: "البلد"},
	{surah:"91", name: "الشمس"},
	{surah:"92", name: "الليل"},
	{surah:"93", name: "الضحى"},
	{surah:"94", name: "الشرح"},
	{surah:"95", name: "التين"},
	{surah:"96", name: "العلق"},
	{surah:"97", name: "القدر"},
	{surah:"98", name: "البينة"},
	{surah:"99", name: "الزلزلة"},
	{surah:"100", name: "العاديات"},
	{surah:"101", name: "القارعة"},
	{surah:"102", name: "التكاثر"},
	{surah:"103", name: "العصر"},
	{surah:"104", name: "الهمزة"},
	{surah:"105", name: "الفيل"},
	{surah:"106", name: "قريش"},
	{surah:"107", name: "الماعون"},
	{surah:"108", name: "الكوثر"},
	{surah:"109", name: "الكافرون"},
	{surah:"110", name: "النصر"},
	{surah:"111", name: "المسد"},
	{surah:"112", name: "الإخلاص"},
	{surah:"113", name: "الفلق"},
	{surah:"114", name: "الناس"},
    {surah:"22", name:"Al-Fatihah"},
    {surah:"116", name:"Al-Baqarah"},
    {surah:"117", name:"Al-Imran"},
    {surah:"118", name:"Al-Nisa"},
    {surah:"119", name:"Al-Maidah"},
    {surah:"120", name:"Al-Anam"},
    {surah:"121", name:"Al-Araf"},
    {surah:"123", name:"Al-Anfal"},
    {surah:"124", name:"At-Tawbah"},
    {surah:"125", name:"Yunus"},
    {surah:"126", name:"Hud"},
    {surah:"127", name: "Yusuf"},
    {surah:"128", name:"Ar-Rad"},
    {surah:"129", name:"Ibraheem"},
    {surah:"130", name: "Al-Hijr"},
    {surah:"131", name: "Al-Nahl"},
    {surah:"132", name: "Al-Isra"},
    {surah:"133", name: "Al-Kahf"},
    {surah:"134", name:"Maryam"},
    {surah:"135", name:"Taha"},
    {surah:"136", name:"Al-Anbiya"},
    {surah:"137", name: "Al-Hajj"},
    {surah:"138", name:"Al-Muminoon"},
    {surah:"139", name:  "Al-Nur"},
    {surah:"140", name:"Al-Furqan"},
    {surah:"141", name:"Ash-Shurara"},
    {surah:"142", name:"An-Naml"},
    {surah:"143", name:  "Al-Qasas"},
    {surah:"144", name: "Al-Ankabut"},
    {surah:"145", name:   "Al-Room"},
    {surah:"146", name: "Luqman"},
    {surah:"147", name:"Al-Sajdah"},
    {surah:"148", name: "Al-Ahzab"},
    {surah:"149", name: "Saba"},
    {surah:"150", name:"Fatir"},
    {surah:"151", name:  "Yaseen"},
    {surah:"152", name:"Al-Saffat"},
    {surah:"153", name: "Sad"},
    {surah:"154", name: "Al-Zumar"},
    {surah:"155", name: "Ghafir"},
    {surah:"156", name: "Fussilat"},
    {surah:"157", name: "Al-Shura"},
    {surah:"158", name:  "Al-Zukhruf"},
    {surah:"159", name:  "Al-Dukhan"},
    {surah:"160", name:"Al-Jathiyah"},
    {surah:"161", name: "Al-Ahqaf"},
    {surah:"162", name: "Muhammad"},
    {surah:"163", name:  "Al-Fath"},
    {surah:"164", name: "Al-Hujurat"},
    {surah:"165", name: "Qaf"},
    {surah:"166", name: "Al-Dhariyat"},
    {surah:"167", name: "Al-Tur"},
    {surah:"168", name:  "Al-Najm"},
    {surah:"169", name:  "Al-Qamar"},
    {surah:"170", name:   "Al--Rahman"},
    {surah:"171", name: "Al-Waqiah"},
    {surah:"172", name: "Al-Hadeed"},
    {surah:"173", name: "Al-Mujadilah"},
    {surah:"174", name: "Al-Hashr"},
    {surah:"175", name:   "Al-Mumtahanah"},
    {surah:"176", name: "Al-Saff"},
    {surah:"177", name:   "Al-Jumuah"},
    {surah:"178", name:   "Al-Munafiqun"},
    {surah:"179", name: "Al-Taghabun"},
    {surah:"180", name: "Al-Talaq"},
    {surah:"181", name:  "Al-Tahreem"},
    {surah:"182", name:  "Al-Mulk"},
    {surah:"183", name:"Al-Qalam"},
    {surah:"184", name: "Al-Haqqah"},
    {surah:"185", name: "Al-Ma'aarij"},
    {surah:"186", name: "Nuh"},
    {surah:"187", name: "Al-Jinn"},
    {surah:"188", name:"Al-Muzzammil"},
    {surah:"189", name:  "Al-Muddathir"},
    {surah:"190", name:"Al-Qiyamah"},
    {surah:"191", name:"Al-Insan"},
    {surah:"192", name: "Al-Mursalat"},
    {surah:"193", name: "Al-Naba"},
    {surah:"194", name: "An-Naziat"},
    {surah:"195", name: "Abasa"},
    {surah:"196", name: "Al-Takweer"},
    {surah:"197", name:  "Al-Infitar"},
    {surah:"198", name: "Al-Mutaffifeen"},
    {surah:"199", name:  "Al-Inshiqaq"},
    {surah:"200", name: "Al-Burooj"},
    {surah:"201", name:    "Al-Tariq"},
    {surah:"202", name: "Al-Ala"},
    {surah:"203", name:  "Al-Ghashiyah"},
    {surah:"204", name: "Al-Fajr"},
    {surah:"205", name:  "Al-Balad"},
    {surah:"206", name:   "Al-Shams"},
    {surah:"207", name:   "Al-Lail"},
    {surah:"208", name:   "Al-Dhuha"},
    {surah:"209", name:   "Al-Inshirah"},
    {surah:"210", name:   "Al-Teen"},
    {surah:"211", name:"Al-Alaq"},
    {surah:"212", name: "Al-Qadr"},
    {surah:"213", name:  "Al-Bayyinah"},
    {surah:"214", name:"Al-Zalzala"},
    {surah:"215", name:  "Al-Adiyat"},
    {surah:"216", name: "Al-Qariah"},
    {surah:"217", name: "Al-Takathur"},
    {surah:"218", name: "Al-Asr"},
    {surah:"219", name:  "Al-Humazah"},
    {surah:"220", name:  "Al-Feel"},
    {surah:"221", name: "Al-Quraish"},
    {surah:"222", name:  "Al-Maaoun"},
    {surah:"223", name:  "Al-Kawthar"},
    {surah:"224", name:   "Al-Kafiroun"},
    {surah:"225", name:  "Al-Nasr"},
    {surah:"226", name: "Al-Masad"},
    {surah:"227", name:  "Al-Ikhlas"},
    {surah:"228", name:  "Al-Falaq"}, 
    {surah:"229", name:  "Al-Nas"},
    
]