const fs = require('fs');
let surahNames = [
    {id:"1", name: "الفاتحة"},
	{id:"2", name: "البقرة"},
	{id:"3", name: "آل عمران"},
	{id:"4", name: "النساء"},
	{id:"5", name: "المائدة"},
	{id:"6", name: "الأنعام"},
	{id:"7", name: "الأعراف"},
	{id:"8", name: "الأنفال"},
	{id:"9", name: "التوبة"},
	{id:"10", name: "يونس"},
	{id:"11", name: "هود"},
	{id:"12", name: "يوسف"},
	{id:"13", name: "الرعد"},
	{id:"14", name: "ابراهيم"},
	{id:"15", name: "الحجر"},
	{id:"16", name: "النحل"},
	{id:"17", name: "الإسراء"},
	{id:"18", name: "الكهف"},
	{id:"19", name: "مريم"},
	{id:"20", name: "طه"},
	{id:"21", name: "الأنبياء"},
	{id:"22", name: "الحج"},
	{id:"23", name: "المؤمنون"},
	{id:"24", name: "النور"},
	{id:"25", name: "الفرقان"},
	{id:"26", name: "الشعراء"},
	{id:"27", name: "النمل"},
	{id:"28", name: "القصص"},
	{id:"29", name: "العنكبوت"},
	{id:"30", name: "الروم"},
	{id:"31", name: "لقمان"},
	{id:"32", name: "السجدة"},
	{id:"33", name: "الأحزاب"},
	{id:"34", name: "سبإ"},
	{id:"35", name: "فاطر"},
	{id:"36", name: "يس"},
	{id:"37", name: "الصافات"},
	{id:"38", name: "ص"},
	{id:"39", name: "الزمر"},
	{id:"40", name: "غافر"},
	{id:"41", name: "فصلت"},
	{id:"42", name: "الشورى"},
	{id:"43", name: "الزخرف"},
	{id:"44", name: "الدخان"},
	{id:"45", name: "الجاثية"},
	{id:"46", name: "الأحقاف"},
	{id:"47", name: "محمد"},
	{id:"48", name: "الفتح"},
	{id:"49", name: "الحجرات"},
	{id:"50", name: "ق"},
	{id:"51", name: "الذاريات"},
	{id:"52", name: "الطور"},
	{id:"53", name: "النجم"},
	{id:"54", name: "القمر"},
	{id:"55", name: "الرحمن"},
	{id:"56", name: "الواقعة"},
	{id:"57", name: "الحديد"},
	{id:"58", name: "المجادلة"},
	{id:"59", name: "الحشر"},
	{id:"60", name: "الممتحنة"},
	{id:"61", name: "الصف"},
	{id:"62", name: "الجمعة"},
	{id:"63", name: "المنافقون"},
	{id:"64", name: "التغابن"},
	{id:"65", name: "الطلاق"},
	{id:"66", name: "التحريم"},
	{id:"67", name: "الملك"},
	{id:"68", name: "القلم"},
	{id:"69", name: "الحاقة"},
	{id:"70", name: "المعارج"},
	{id:"71", name: "نوح"},
	{id:"72", name: "الجن"},
	{id:"73", name: "المزمل"},
	{id:"74", name: "المدثر"},
	{id:"75", name: "القيامة"},
	{id:"76", name: "الانسان"},
	{id:"77", name: "المرسلات"},
	{id:"78", name: "النبإ"},
	{id:"79", name: "النازعات"},
	{id:"80", name: "عبس"},
	{id:"81", name: "التكوير"},
	{id:"82", name: "الإنفطار"},
	{id:"83", name: "المطففين"},
	{id:"84", name: "الإنشقاق"},
	{id:"85", name: "البروج"},
	{id:"86", name: "الطارق"},
	{id:"87", name: "الأعلى"},
	{id:"88", name: "الغاشية"},
	{id:"89", name: "الفجر"},
	{id:"90", name: "البلد"},
	{id:"91", name: "الشمس"},
	{id:"92", name: "الليل"},
	{id:"93", name: "الضحى"},
	{id:"94", name: "الشرح"},
	{id:"95", name: "التين"},
	{id:"96", name: "العلق"},
	{id:"97", name: "القدر"},
	{id:"98", name: "البينة"},
	{id:"99", name: "الزلزلة"},
	{id:"100", name: "العاديات"},
	{id:"101", name: "القارعة"},
	{id:"102", name: "التكاثر"},
	{id:"103", name: "العصر"},
	{id:"104", name: "الهمزة"},
	{id:"105", name: "الفيل"},
	{id:"106", name: "قريش"},
	{id:"107", name: "الماعون"},
	{id:"108", name: "الكوثر"},
	{id:"109", name: "الكافرون"},
	{id:"110", name: "النصر"},
	{id:"111", name: "المسد"},
	{id:"112", name: "الإخلاص"},
	{id:"113", name: "الفلق"},
	{id:"114", name: "الناس"},
    {id:"115", name:"Al-Fatihah"},
    {id:"116", name:"Al-Baqarah"},
    {id:"117", name:"Al-Imran"},
    {id:"118", name:"Al-Nisa"},
    {id:"119", name:"Al-Maidah"},
    {id:"120", name:"Al-Anam"},
    {id:"121", name:"Al-Araf"},
    {id:"122", name:"Al-Anfal"},
    {id:"123", name:"At-Tawbah"},
    {id:"124", name:"Yunus"},
    {id:"125", name:"Hud"},
    {id:"126", name: "Yusuf"},
    {id:"127", name:"Ar-Rad"},
    {id:"128", name:"Ibraheem"},
    {id:"129", name: "Al-Hijr"},
    {id:"130", name: "Al-Nahl"},
    {id:"131", name: "Al-Isra"},
    {id:"132", name: "Al-Kahf"},
    {id:"133", name:"Maryam"},
    {id:"134", name:"Taha"},
    {id:"135", name:"Al-Anbiya"},
    {id:"136", name: "Al-Hajj"},
    {id:"137", name:"Al-Muminoon"},
    {id:"138", name:  "Al-Nur"},
    {id:"139", name:"Al-Furqan"},
    {id:"140", name:"Ash-Shurara"},
    {id:"141", name:"An-Naml"},
    {id:"142", name:  "Al-Qasas"},
    {id:"143", name: "Al-Ankabut"},
    {id:"144", name:   "Al-Room"},
    {id:"145", name: "Luqman"},
    {id:"146", name:"Al-Sajdah"},
    {id:"147", name: "Al-Ahzab"},
    {id:"148", name: "Saba"},
    {id:"149", name:"Fatir"},
    {id:"150", name:  "Yaseen"},
    {id:"151", name:"Al-Saffat"},
    {id:"152", name: "Sad"},
    {id:"153", name: "Al-Zumar"},
    {id:"154", name: "Ghafir"},
    {id:"155", name: "Fussilat"},
    {id:"156", name: "Al-Shura"},
    {id:"157", name:  "Al-Zukhruf"},
    {id:"158", name:  "Al-Dukhan"},
    {id:"159", name:"Al-Jathiyah"},
    {id:"160", name: "Al-Ahqaf"},
    {id:"161", name: "Muhammad"},
    {id:"162", name:  "Al-Fath"},
    {id:"163", name: "Al-Hujurat"},
    {id:"164", name: "Qaf"},
    {id:"165", name: "Al-Dhariyat"},
    {id:"166", name: "Al-Tur"},
    {id:"167", name:  "Al-Najm"},
    {id:"168", name:  "Al-Qamar"},
    {id:"169", name:   "Al--Rahman"},
    {id:"170", name: "Al-Waqiah"},
    {id:"171", name: "Al-Hadeed"},
    {id:"172", name: "Al-Mujadilah"},
    {id:"173", name: "Al-Hashr"},
    {id:"174", name:   "Al-Mumtahanah"},
    {id:"175", name: "Al-Saff"},
    {id:"176", name:   "Al-Jumuah"},
    {id:"177", name:   "Al-Munafiqun"},
    {id:"178", name: "Al-Taghabun"},
    {id:"179", name: "Al-Talaq"},
    {id:"180", name:  "Al-Tahreem"},
    {id:"181", name:  "Al-Mulk"},
    {id:"182", name:"Al-Qalam"},
    {id:"183", name: "Al-Haqqah"},
    {id:"184", name: "Al-Ma'aarij"},
    {id:"185", name: "Nuh"},
    {id:"186", name: "Al-Jinn"},
    {id:"187", name:"Al-Muzzammil"},
    {id:"188", name:  "Al-Muddathir"},
    {id:"189", name:"Al-Qiyamah"},
    {id:"190", name:"Al-Insan"},
    {id:"191", name: "Al-Mursalat"},
    {id:"192", name: "Al-Naba"},
    {id:"193", name: "An-Naziat"},
    {id:"194", name: "Abasa"},
    {id:"195", name: "Al-Takweer"},
    {id:"196", name:  "Al-Infitar"},
    {id:"197", name: "Al-Mutaffifeen"},
    {id:"198", name:  "Al-Inshiqaq"},
    {id:"199", name: "Al-Burooj"},
    {id:"200", name:    "Al-Tariq"},
    {id:"201", name: "Al-Ala"},
    {id:"202", name:  "Al-Ghashiyah"},
    {id:"203", name: "Al-Fajr"},
    {id:"204", name:  "Al-Balad"},
    {id:"205", name:   "Al-Shams"},
    {id:"206", name:   "Al-Lail"},
    {id:"207", name:   "Al-Dhuha"},
    {id:"208", name:   "Al-Inshirah"},
    {id:"209", name:   "Al-Teen"},
    {id:"210", name:"Al-Alaq"},
    {id:"211", name: "Al-Qadr"},
    {id:"212", name:  "Al-Bayyinah"},
    {id:"213", name:"Al-Zalzala"},
    {id:"214", name:  "Al-Adiyat"},
    {id:"215", name: "Al-Qariah"},
    {id:"216", name: "Al-Takathur"},
    {id:"217", name: "Al-Asr"},
    {id:"218", name:  "Al-Humazah"},
    {id:"219", name:  "Al-Feel"},
    {id:"220", name: "Al-Quraish"},
    {id:"221", name:  "Al-Maaoun"},
    {id:"222", name:  "Al-Kawthar"},
    {id:"223", name:   "Al-Kafiroun"},
    {id:"224", name:  "Al-Nasr"},
    {id:"225", name: "Al-Masad"},
    {id:"226", name:  "Al-Ikhlas"},
    {id:"227", name:  "Al-Falaq"}, 
    {id:"228", name:  "Al-Nas"},
    
];

let newList = []
for(let i = 0; i< 114; i++){
    newList.push({...surahNames[i], ename: surahNames[i+114].name});
}

fs.writeFile("./newNames.js", JSON.stringify(newList), function(err) {
    if(err) {
        return console.log(err);
    }
    console.log("The file was saved!");
}); 

// Or
fs.writeFileSync('/tmp/test-sync', 'Hey there!');